# Generated by Django 5.0.7 on 2024-09-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('bid', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
