# Generated by Django 5.0.7 on 2024-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_create_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home')], max_length=20),
        ),
    ]
